---
title: "Boxplot Results"
author: "Avery Moorhead"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/avery/OneDrive/Desktop/MaterialDemand/Outputs")

library(readxl)
library(dplyr)
library(ggplot2)

```


```{r}
setwd("C:/Users/avery/OneDrive/Desktop/MaterialDemand/Outputs")
repeat_mc_material_demand<- read.csv("repeat_mc_material_demand.csv")
multi_model_mc_material_demand<- read.csv("multi_model_mc_material_demand.csv")
repeat_materials_demand<- read.csv("repeat_materials_demand.csv")
print(unique(repeat_materials_demand$technology))
materials_demand<-read.csv("materials_demand.csv")
multi_model_mc_material_demand_total<-read.csv("multi_model_mc_material_demand_total.csv")
transmission_material_sum<-read.csv("transmission_material_sum.csv")
all_models<-read.csv("all_models_material_demand.csv")
repeat_mc_material_demand_total<-read.csv("repeat_mc_material_demand_total.csv")
```


```{r}
# plot_list <- list()
# 
# materials <- c("Aluminum", "Boron",  "Cement", "Chromium", "Copper", "Dysprosium", "Fiberglass", "Glass", "Lead",  "Manganese","Molybdenum","Neodymium","Nickel", "Niobium", "Praseodymium",  "Silicon", "Silver", "Steel",  "Terbium", "Vanadium", "Yttrium", "Zinc")
# 
# 
# for (material in materials) {
#   material_demand_sum <- repeat_materials_demand %>%
#     group_by(year, scenario) %>%
#     summarise(
#       !!paste0(material, "_mean") := sum(!!sym(paste0(material, "_mean"))),
#       !!paste0(material, "_min") := sum(!!sym(paste0(material, "_min"))),
#       !!paste0(material, "_max") := sum(!!sym(paste0(material, "_max")))
#     )
#   
#   material_demand_sum_ira <- material_demand_sum %>%
#     filter(scenario == "IRA")
#   
#   material_demand_sum_ref <- material_demand_sum %>%
#     filter(scenario == "REF")
#   
#   # Plot the data for IRA scenario
#   p <- ggplot() +
#     geom_line(data = material_demand_sum_ira, aes(x = year, 
#                                                   y = !!sym(paste0(material, "_mean")), 
#                                                   color = "mean IRA"), 
#               linetype = "solid") +
#     geom_line(data = material_demand_sum_ira, aes(x = year, 
#                                                   y = !!sym(paste0(material, "_min")), 
#                                                   color = "min IRA"), 
#               linetype = "dashed") +
#     geom_line(data = material_demand_sum_ira, aes(x = year, 
#                                                   y = !!sym(paste0(material, "_max")), 
#                                                   color = "max IRA"), 
#               linetype = "dotted") +
#     # Plot the data for Ref scenario
#     geom_line(data = material_demand_sum_ref, aes(x = year, 
#                                                   y = !!sym(paste0(material, "_mean")), 
#                                                   color = "mean Ref"), 
#               linetype = "solid") +
#     geom_line(data = material_demand_sum_ref, aes(x = year, 
#                                                   y = !!sym(paste0(material, "_min")), 
#                                                   color = "min Ref"), 
#               linetype = "dashed") +
#     geom_line(data = material_demand_sum_ref, aes(x = year, 
#                                                   y = !!sym(paste0(material, "_max")), 
#                                                   color = "max Ref"), 
#               linetype = "dotted") +
#     labs(title = paste(material),
#          x = "",
#          y = "",
#          color = "Scenario") +
#     scale_color_manual(values = c("mean IRA" = "red", "min IRA" = "red", "max IRA" = "red",
#                                   "mean Ref" = "blue", "min Ref" = "blue", "max Ref" = "blue"),
#                        labels = c("Mean IRA", "Min IRA", "Max IRA", "Mean Ref", "Min Ref", "Max Ref"),
#                        breaks = c("mean IRA", "min IRA", "max IRA", "mean Ref", "min Ref", "max Ref")) +
#     scale_x_continuous(breaks = c(2025, 2030, 2035)) +
#     theme_minimal() +
#     theme(legend.position = "none",
#            axis.text.x = element_text(size = 14), 
#       axis.text.y = element_text(size = 14), 
#       axis.title.x = element_text(size = 16),
#       axis.title.y = element_text(size = 16), 
#       plot.title = element_text(size = 20, hjust = 0.5))
#   
#   material_subset_ira <- repeat_mc_material_demand_total %>%
#     filter(Material == material, year == 2035, scenario == "IRA") %>%
#     select(-total_demand, -year, -scenario, -Material, -row_id) %>%
#     mutate(
#       across(c(onshore.wind, offshore.wind, Nuclear.New, utility.scale.solar.pv, Gas), ~sort(.)),
#       total_demand = (onshore.wind + offshore.wind + Nuclear.New + utility.scale.solar.pv + Gas) / 1000,
#       year = 2035
#     )
#   
#   material_subset_ref <- repeat_mc_material_demand_total %>%
#     filter(Material == material, year == 2035, scenario == "REF") %>%
#     select(-total_demand, -year, -scenario, -Material, -row_id) %>%
#     mutate(
#       across(c(onshore.wind, Nuclear.New, utility.scale.solar.pv, offshore.wind, Gas), ~sort(.)),
#       total_demand = (onshore.wind + offshore.wind + Nuclear.New + utility.scale.solar.pv + Gas) / 1000,
#       year = 2035
#     )
#   
#   boxplot_ira <- geom_boxplot(data = material_subset_ira, aes(x = year, y = total_demand), fill = "red", alpha = 0.5, width = 0.5)
#   boxplot_ref <- geom_boxplot(data = material_subset_ref, aes(x = year, y = total_demand), fill = "blue", alpha = 0.5, width = 0.5)
#   
#   p <- p + boxplot_ira + boxplot_ref
#   
#   plot_list[[material]] <- p
# }
# 
# combined_plot <- cowplot::plot_grid(plotlist = plot_list, ncol = 3)
# print(combined_plot)
# 
# ggsave("repeat_complete_boxplot.jpg", plot = combined_plot, width = 11, height = 14, units = "in", dpi = 300)
# 

```


**Plot Bistline et al. (202x). The boxplots are the simulated material demand and the lines are the min max and mean individual model values **
```{r}

plot_list <- list()

materials <- c("Aluminum", "Boron",  "Cement", "Chromium", "Copper", "Dysprosium", "Fiberglass", "Glass", "Lead", "Magnesium", "Manganese","Molybdenum","Neodymium","Nickel", "Niobium", "Praseodymium",  "Silicon", "Silver", "Steel",  "Terbium","Tin", "Vanadium", "Yttrium", "Zinc")

for (material in materials) {
  material_demand_sum_mean <- materials_demand %>%
    group_by(year, scenario) %>%
    summarise(
      !!paste0(material, "_mean") := sum(!!sym(paste0(material, "_mean"))),
      !!paste0(material, "_min") := sum(!!sym(paste0(material, "_min"))),
      !!paste0(material, "_max") := sum(!!sym(paste0(material, "_max")))
    )
  
  sum_material_columns <- function(data, material) {
    material_demand_sum_df <- data %>%
      select(year, scenario, technology, model, 
             matches(paste0(material, "_mean")), 
             matches(paste0(material, "_max")), 
             matches(paste0(material, "_min"))) %>%
      group_by(year, scenario, model) %>%
      summarise(
        !!paste0(material, "_min") := sum(!!sym(paste0(material, "_min")), na.rm = TRUE),
        !!paste0(material, "_max") := sum(!!sym(paste0(material, "_max")), na.rm = TRUE)
      ) %>%
      group_by(year, scenario) %>%
      summarise(
        !!paste0(material, "_min") := min(!!sym(paste0(material, "_min")), na.rm = TRUE),
        !!paste0(material, "_max") := max(!!sym(paste0(material, "_max")), na.rm = TRUE)
      )
    
    return(material_demand_sum_df)
  }
  
  material_demand_sum <- sum_material_columns(all_models, material)
  material_demand_sum_ira <- material_demand_sum %>%
    filter(scenario == "IRA")
  
  material_demand_sum_ref <- material_demand_sum %>%
    filter(scenario == "Ref")
  
  material_demand_sum_ira_mean <-  material_demand_sum_mean %>%
    filter(scenario == "IRA")
  
  material_demand_sum_ref_mean <-  material_demand_sum_mean %>%
    filter(scenario == "Ref")
  
  
  # Plot the data for IRA scenario
  p <- ggplot() +
    geom_line(data = material_demand_sum_ira_mean, aes(x = year, 
                                                       y = !!sym(paste0(material, "_mean")), 
                                                       color = "mean IRA"), 
              linetype = "solid") +
    geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                  y = !!sym(paste0(material, "_min")), 
                                                  color = "min IRA"), 
              linetype = "dashed") +
    geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                  y = !!sym(paste0(material, "_max")), 
                                                  color = "max IRA"), 
              linetype = "dotted") +
    # Plot the data for Ref scenario
    geom_line(data = material_demand_sum_ref_mean, aes(x = year, 
                                                       y = !!sym(paste0(material, "_mean")), 
                                                       color = "mean Ref"), 
              linetype = "solid") +
    geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                  y = !!sym(paste0(material, "_min")), 
                                                  color = "min Ref"), 
              linetype = "dashed") +
    geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                  y = !!sym(paste0(material, "_max")), 
                                                  color = "max Ref"), 
              linetype = "dotted") +
    labs(title = paste(material),
         x = "",
         y = "",
         color = "Scenario") +
    scale_color_manual(values = c("mean IRA" = "red", "min IRA" = "red", "max IRA" = "red",
                                  "mean Ref" = "blue", "min Ref" = "blue", "max Ref" = "blue"),
                       labels = c("Mean IRA", "Min IRA", "Max IRA", "Mean Ref", "Min Ref", "Max Ref"),
                       breaks = c("mean IRA", "min IRA", "max IRA", "mean Ref", "min Ref", "max Ref")) +
    scale_x_continuous(breaks = c(2025, 2030, 2035)) +
    theme_minimal() +
    theme(legend.position = "none",
          axis.text.x = element_text(size = 14),
          axis.text.y = element_text(size = 14), 
          axis.title.x = element_text(size = 16), 
          axis.title.y = element_text(size = 16),
          plot.title = element_text(size = 20, hjust = 0.5))
  
  material_subset_ira <- multi_model_mc_material_demand_total %>%
    
    filter(Material == material, year == 2035, scenario == "IRA") %>%
    select(total_demand, year, -scenario, -Material, -row_id) #%>%
  
  material_subset_ref <- multi_model_mc_material_demand_total %>%
    filter(Material == material, year == 2035, scenario == "Ref") %>%
    select(total_demand, year, -scenario, -Material, -row_id) #%>%
  
  # Create box plots for IRA and Ref scenarios
  boxplot_ira <- geom_boxplot(data = material_subset_ira, aes(x = year, y = total_demand/1000), fill = "red", alpha = 0.5, width = 0.5)
  boxplot_ref <- geom_boxplot(data = material_subset_ref, aes(x = year, y = total_demand/1000), fill = "blue", alpha = 0.5, width = 0.5)
  
  # Combine boxplots with the lines
  p <- p + boxplot_ira + boxplot_ref
  plot_list[[material]] <- p
}
print(p)
# Combine all material subplots together
combined_plot <- cowplot::plot_grid(plotlist = plot_list, ncol = 4)
print(combined_plot)

ggsave("multi_model_complete_boxplot.jpg", plot = combined_plot, width = 13, height = 17, units = "in", dpi = 300)
```

```



