---
title: "Material Intensity Distribution Fitting"
author: "Avery Moorhead"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/avery/OneDrive/Desktop/MaterialDemand/Raw Data")
library(tibble)
library(fitdistrplus)
library(readxl)
```
**Processing Material Intensity Data**
```{r}
#loading data
material_intensity = read_excel("Final Intensity Values.xlsx", sheet = "Intensity Values", range = cell_cols(1:6))

#processing data
colnames(material_intensity)[1] ="technology"
colnames(material_intensity)[3] ="value"
material_intensity <- material_intensity[!duplicated(material_intensity), ]
material_intensity <- material_intensity[material_intensity$`Year of the data` <= 2025, 
                                  !(names(material_intensity) %in% c('Year of the data', 'Authors', 'Publish year'))]
material_intensity["technology"][material_intensity["technology"] == "Nuclear"] <- "Nuclear New"
material_intensity["technology"][material_intensity["technology"] == "Onshore_AG"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Onshore_DD_PMG"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Wind Directed_Drive"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Geared"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Wind onshore"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Wind Onshore"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Onshore Wind"] <- "onshore wind"
material_intensity["technology"][material_intensity["technology"] == "Offshore Wind"] <- "Wind Offshore"
material_intensity["technology"][material_intensity["technology"] == "CSI_PV"] <- "utility-scale solar pv"
material_intensity$technology[material_intensity$technology == "Offshore_DD_PMG"] <- "Wind Offshore"
material_intensity$technology[material_intensity$technology == "Offshore_AG"] <- "Wind Offshore"
material_intensity$Material[material_intensity$Material == "Neodymium "] <-  "Neodymium"

```


```{r}
library(dplyr)

# Counting occurrences of each technology and material and filter to find combinations over 30 
count_table <- material_intensity %>%
  group_by(technology, Material) %>%
  summarise(count = n())
material_intensity_dist_df <- material_intensity %>%
  inner_join(count_table, by = c("technology", "Material")) %>%
  filter(count >= 30)
material_intensity_dist_df <- material_intensity_dist_df %>%
  filter(!(technology %in% c("CIGS", "CdTe")))

#finding unique technologies for the for loop
unique_technologies <- unique(material_intensity_dist_df$technology)

combinations <- list()

# Looping through each technology 
for (tech in unique_technologies) {
  materials <- material_intensity_dist_df %>%
    filter(technology == tech) %>%
    select(Material) %>%
    distinct() %>%
    pull()
  tech_combinations <- lapply(materials, function(mat) list(technology = tech, Material = mat))
  
  combinations <- c(combinations, tech_combinations)
}
lowest_aic_results <- data.frame()

for (combo in combinations) {
  subset_data <- subset(material_intensity_dist_df, 
                        technology == combo[["technology"]] & Material == combo[["Material"]])
    fits <- list()
  distributions <- c("weibull", "gamma", "exp","triang","norm") #fitting distributions 
  for (dist in distributions) {
    tryCatch({
      fit <- fitdist(subset_data$value, dist)
      fits[[dist]] <- fit
    }, error = function(e) {
      fits[[dist]] <- NULL
    })
  }
    fits <- fits[!sapply(fits, is.null)]
  
  if (length(fits) > 0) {
    aic_values <- sapply(fits, function(fit) fit$aic)
    aic_df <- data.frame(Distribution = names(fits), AIC = aic_values)
    
    # Finding the distribution with the lowest AIC
    lowest_aic_row <- aic_df[aic_df$AIC == min(aic_df$AIC), ]
    lowest_aic_row$technology <- combo[["technology"]]
    lowest_aic_row$Material <- combo[["Material"]]
    lowest_aic_results <- rbind(lowest_aic_results, lowest_aic_row)
  }
}

final_aic_results <- lowest_aic_results  %>% filter(!(technology %in% c("CIGS", "CdTe")))
final_aic_results <- remove_rownames(final_aic_results)

#fitting normal distribution to all combinations with under 30 values
less_than_30_count <- material_intensity %>%
  inner_join(count_table, by = c("technology", "Material")) %>%
  filter(count < 30) %>%
  distinct(Material, technology) %>%  filter(!technology %in% c("a-Si", "ASIGE", "BiomassCCS", "CdTe", "CDTE", "CIGS", "Coal", "CoalCCS", "Gas", "GasCCS"))%>%   mutate(AIC = NA) %>%   mutate(Distribution = "norm")

final_aic_results <- bind_rows(less_than_30_count, final_aic_results)
```
**Writing data to be used in the model**
```{r}
folder_path <- "C:/Users/avery/OneDrive/Desktop/MaterialDemand/Inputs"
file_path1 <- file.path(folder_path, "distribution_fitting_results.csv")
write.csv(final_aic_results, file = file_path1, row.names = FALSE)


```


