---
title: "Results Simulation Visualisation"
output: html_notebook
---


```{r}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/avery/OneDrive/Desktop/MaterialDemand/Outputs")

library(readxl)
library(dplyr)
```

```{r}
print(getwd())
setwd("C:/Users/avery/OneDrive/Desktop/MaterialDemand/Outputs")
repeat_mc_material_demand<- read.csv("repeat_mc_material_demand.csv")
multi_model_mc_material_demand<- read.csv("multi_model_mc_material_demand.csv")
repeat_materials_demand<- read.csv("repeat_materials_demand.csv")

materials_demand<-read.csv("materials_demand.csv")
multi_model_mc_material_demand_total<-read.csv("multi_model_mc_material_demand_total.csv")
transmission_material_sum<-read.csv("transmission_material_sum.csv")


repeat_mc_material_demand_total<-read.csv("repeat_mc_material_demand_total.csv")

setwd("C:/Users/avery/OneDrive/Desktop/MaterialDemand/Inputs")

#material_intensity <- read.csv("intensity_data.csv")
#initial_year<-read.csv("initial_year.csv")
#multi_model_capacities<-read.csv("multi_model_capacities.csv")
#repeat_capacities_new<-read.csv("repeat_capacities_new.csv")


```

```{r}
library(tidyr)

# Modify the transmission_material_sum data frame and create transmission_for_plot
transmission_for_plot <- transmission_material_sum %>%
  mutate(
    technology = "transmission",  # Add a new column "technology" with value "transmission"
    Aluminum_mean = Aluminum,     # Rename Aluminum column
    Copper_mean = Cu,             # Rename Cu column to Copper_mean
    Steel_mean = Steel,           # Rename Steel column
    Cement_mean = Cement,         # Rename Cement column
    Glass_mean = Glass,
    scenario = if_else(scenario == "REF", "Ref", scenario)  # Rename "REF" to "Ref" in the scenario column
  ) %>%
  select(-Aluminum, -Cu, -Steel, -Cement,-Glass)  # Remove original columns



# Identify columns that exist in repeat_material_demand but not in transmission_for_plot
missing_columns <- setdiff(names(repeat_materials_demand), names(transmission_for_plot))

# Add missing columns to transmission_for_plot if they don't already exist
for (col in missing_columns) {
  if (!col %in% names(transmission_for_plot)) {
    transmission_for_plot[[col]] <- 0
  }
}

# Print the updated transmission_for_plot data frame
print(transmission_for_plot)

repeat_materials_demand<-rbind(transmission_for_plot,repeat_materials_demand)
# Identify columns that exist in repeat_material_demand but not in transmission_for_plot
missing_columns <- setdiff(names(repeat_materials_demand), names(transmission_for_plot))

library(dplyr)

library(dplyr)

# Print the missing columns
print(missing_columns)
missing_columns <- setdiff(names(transmission_for_plot), names(repeat_materials_demand))
print(missing_columns)


print(ncol(repeat_materials_demand))
print(ncol(transmission_for_plot))


```

```{r}
# Load required library
library(ggplot2)
library(scales)  # For number formatting

plot_df <- subset(materials_demand, select = c('scenario', 'year', 'technology', 'Aluminum_mean'))
trans_plot_df<- subset(transmission_material_sum, select = c('scenario', 'year', 'Aluminum'))
trans_plot_df <- trans_plot_df %>%
  mutate(technology = "transmission") %>%
  rename(Aluminum_mean = Aluminum)
plot_df <- rbind(plot_df, trans_plot_df)

plot_df <- subset(plot_df, scenario == "IRA" | is.na(scenario))
#plot_df$year <- ifelse(is.na(plot_df$year), 2021, plot_df$year)
#plot_df <- subset(materials_demand, year != 2021, select = c('scenario', 'year', 'technology', 'Aluminum_mean'))

head(plot_df)
plot_df <- plot_df %>%
  filter(scenario == "IRA")
plot_df <- plot_df %>%
  mutate(
    technology = case_when(
      technology == "Nuclear New" ~ "Nuclear",
      technology == "onshore wind" ~ "Onshore Wind",
      technology == "offshore wind" ~ "Offshore Wind",
      technology == "transmission" ~ "Transmission",
      technology == "utility-scale solar pv" ~ "Utility-scale Solar PV",
      TRUE ~ technology
    )
  )

repeat_materials_demand <- repeat_materials_demand %>% 
  mutate(
    scenario = case_when(
      scenario == "REF" ~ "Ref",
      TRUE ~ scenario
    )
  )




# Convert year to integer
plot_df$year <- as.integer(plot_df$year)


# Create the plot
ggplot(plot_df, aes(x = year, y = Aluminum_mean, fill = technology)) +
  geom_area() +
  labs(title = "IRA Aluminum Material Demand",
       x = "Year",
       y = "Material Demand") +
  theme_minimal() +
  scale_y_continuous(labels = comma) +  # Format y-axis labels without scientific notation
  scale_x_continuous(breaks = c(2025, 2030, 2035))  # Set specific x-axis breaks

# Create the plot


```


```{r}
materials_demand <- materials_demand %>%
  mutate(
    technology = case_when(
      technology == "Nuclear New" ~ "Nuclear",
      technology == "onshore wind" ~ "Onshore Wind",
      technology == "offshore wind" ~ "Offshore Wind",
      technology == "transmission" ~ "Transmission",
      technology == "utility-scale solar pv" ~ "Utility-scale Solar PV",
      TRUE ~ technology
    )
  )

repeat_materials_demand <- repeat_materials_demand %>%
  mutate(
    technology = case_when(
      technology == "Nuclear New" ~ "Nuclear",
      technology == "onshore wind" ~ "Onshore Wind",
      technology == "offshore wind" ~ "Offshore Wind",
      technology == "transmission" ~ "Transmission",
      technology == "utility-scale solar pv" ~ "Utility-scale Solar PV",
      TRUE ~ technology
    )
  )

library(ggplot2)
library(scales)  # For number formatting
library(cowplot)
library(patchwork)
#cut gallium indium selenium
# Create a list of materials
#cutting cadmium,gallium,germanium,indium
#removed tin and neodymium 

#"Molybdenum", "Neodymium", "Nickel", "Niobium", "Praseodymium", "Selenium", "Silicon", "Silver", "Steel", "Tellurium", "Terbium", "Tin", "Vanadium", "Yttrium", "Zinc",)


materials <- c("Aluminum", "Boron",  "Cement", "Chromium", "Copper", "Dysprosium", "Fiberglass", "Glass", "Lead",  "Manganese","Molybdenum","Neodymium")

# Create an empty list to store plots
plot_list <- list()

# Loop through each material
for (material in materials) {
  # Subset the data for the current material and scenario "IRA"
  plot_df <- subset(materials_demand, scenario == "Ref", select = c('year', 'technology', paste0(material, "_mean")))
  
  # Convert year to integer
  plot_df$year <- as.integer(plot_df$year)
  
  # Create the plot for the current material
p <- ggplot(plot_df, aes(x = year, y = !!sym(paste0(material, "_mean")), fill = technology)) +
  geom_area() +
  labs(title = paste(material),
       x = "",
       y = "") +
  theme_minimal() +
  scale_y_continuous(labels = comma) +  # Format y-axis labels without scientific notation
  scale_x_continuous(breaks = c(2025, 2030, 2035)) +  # Set specific x-axis breaks
  theme(
    legend.position = "none",  # Remove the legend
    plot.title = element_text(size = 10)  # Adjust the size of the plot title
  )

  # Store the plot in the plot list
  plot_list[[material]] <- p
}

# Combine all plots in the plot list
combined_plot <- cowplot::plot_grid(plotlist = plot_list, ncol = 5, align = "h", rel_widths = rep(1, length(materials)))

# Create a common legend plot
# Extract the legend from the Aluminum plot
legend_plot <- cowplot::get_legend(plot_list[["Aluminum"]] + theme(legend.position = "right"))

# Manually adjust the widths of the legend and the combined plot
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 0.8, 1) +
  cowplot::draw_plot(legend_plot, 0.8, 0, 0.2, 1)

# Display the final plot
print(final_plot)

# Adjust the width of each plot
plot_width <- 10  # Adjust this value as needed

# Arrange the plots using patchwork
final_plot_with_title <- wrap_plots(plotlist = plot_list, ncol = 4, widths = rep(plot_width, length(plot_list)))

# Add a common y-axis title using cowplot
common_y_axis_title <- ggdraw() +
  draw_label("Material Demand (thousand tonnes)", angle = 90, size = 10, hjust = 0.5, vjust = 0.5) +
  theme(plot.margin = margin(5.5, 5.5, 5.5, 0, "pt"))

# Combine the common y-axis title with the final plot
final_plot_with_title <- cowplot::plot_grid(
  common_y_axis_title,
  final_plot_with_title + theme(plot.margin = margin(5.5, 0, 5.5, 5.5, "pt")),
  nrow = 1,
  rel_widths = c(0.1, 0.9)
)

# Print or display the final plot with the common y-axis title
print(final_plot_with_title)
# Save the combined plot as a PNG file
print(getwd())
ggsave("repeatresultsplotp1.jpg", plot = final_plot_with_title, width = 10, height = 6, units = "in", dpi = 300)


```


```{r}
library(ggplot2)
library(scales)  # For number formatting
library(cowplot)
library(patchwork)
#cut gallium indium selenium
# selenium, tellurium

materials <- c( "Nickel", "Niobium", "Praseodymium",  "Silicon", "Silver", "Steel",  "Terbium", "Vanadium", "Yttrium", "Zinc")

# Create an empty list to store plots
plot_list <- list()

# Loop through each material
for (material in materials) {
  # Subset the data for the current material and scenario "IRA"
  plot_df <- subset(materials_demand, scenario == "Ref", select = c('year', 'technology', paste0(material, "_mean")))
  
  # Convert year to integer
  plot_df$year <- as.integer(plot_df$year)
  
  # Create the plot for the current material
p <- ggplot(plot_df, aes(x = year, y = !!sym(paste0(material, "_mean")), fill = technology)) +
  geom_area() +
  labs(title = paste(material),
       x = "",
       y = "") +
  theme_minimal() +
  scale_y_continuous(labels = comma) +  # Format y-axis labels without scientific notation
  scale_x_continuous(breaks = c(2025, 2030, 2035)) +  # Set specific x-axis breaks
  theme(
    legend.position = "none",  # Remove the legend
    plot.title = element_text(size = 10)  # Adjust the size of the plot title
  )

  # Store the plot in the plot list
  plot_list[[material]] <- p
}

# Combine all plots in the plot list
combined_plot <- cowplot::plot_grid(plotlist = plot_list, ncol = 5, align = "h", rel_widths = rep(1, length(materials)))

# Create a common legend plot
# Extract the legend from the Aluminum plot
legend_plot <- cowplot::get_legend(plot_list[["Aluminum"]] + theme(legend.position = "right"))

# Manually adjust the widths of the legend and the combined plot
final_plot <- cowplot::ggdraw() +
  cowplot::draw_plot(combined_plot, 0, 0, 0.8, 1) +
  cowplot::draw_plot(legend_plot, 0.8, 0, 0.2, 1)

# Display the final plot
print(final_plot)

# Adjust the width of each plot
plot_width <- 10  # Adjust this value as needed

# Arrange the plots using patchwork
final_plot_with_title <- wrap_plots(plotlist = plot_list, ncol = 4, widths = rep(plot_width, length(plot_list)))

# Add a common y-axis title using cowplot
common_y_axis_title <- ggdraw() +
  draw_label("Material Demand (thousand tonnes)", angle = 90, size = 10, hjust = 0.5, vjust = 0.5) +
  theme(plot.margin = margin(5.5, 5.5, 5.5, 0, "pt"))

# Combine the common y-axis title with the final plot
final_plot_with_title <- cowplot::plot_grid(
  common_y_axis_title,
  final_plot_with_title + theme(plot.margin = margin(5.5, 0, 5.5, 5.5, "pt")),
  nrow = 1,
  rel_widths = c(0.1, 0.9)
)

# Print or display the final plot with the common y-axis title
print(final_plot_with_title)
# Save the combined plot as a PNG file
print(getwd())
ggsave("repeatresultsplotp2.jpg", plot = final_plot_with_title, width = 10, height = 6, units = "in", dpi = 300)

```


```{r}
library(ggplot2)
material_demand_sum <- materials_demand %>%
  group_by(year,scenario) %>%
  summarise(Aluminum_mean = sum(Aluminum_mean),
            Aluminum_min = sum(Aluminum_min),
            Aluminum_max = sum(Aluminum_max))
material_demand_sum_ira <- material_demand_sum %>%
  filter(scenario == "IRA")
# Plot the data
material_demand_sum_ref <- material_demand_sum %>%
  filter(scenario == "Ref")
# Plot the data








```


```{r}
library(ggplot2)

# Plot the data for IRA scenario
p <- ggplot() +
  geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                y = Aluminum_mean, 
                                                color = "Aluminum_mean (IRA)"), 
            linetype = "solid") +
  geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                y = Aluminum_min, 
                                                color = "Aluminum_min (IRA)"), 
            linetype = "dashed") +
  geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                y = Aluminum_max, 
                                                color = "Aluminum_max (IRA)"), 
            linetype = "dotted") +
  labs(title = "Annual Aluminum Demand",
       x = "Year",
       y = "Material Demand (Mton/year)",
       color = "Scenario") +
  scale_color_manual(values = c("Aluminum_mean (IRA)" = "red", 
                                "Aluminum_min (IRA)" = "red", 
                                "Aluminum_max (IRA)" = "red", 
                                "Aluminum_mean (Ref)" = "blue", 
                                "Aluminum_min (Ref)" = "blue", 
                                "Aluminum_max (Ref)" = "blue"),  # Color for each line
                     name = "Scenario",
                     labels = c("Mean (IRA)", "Min (IRA)", "Max (IRA)", "Mean (Ref)", "Min (Ref)", "Max (Ref)")) +
  theme_minimal()

# Plot the data for Ref scenario and combine with the previous plot
p +
  geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                y = Aluminum_mean, 
                                                color = "Aluminum_mean (Ref)"), 
            linetype = "solid") +
  geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                y = Aluminum_min, 
                                                color = "Aluminum_min (Ref)"), 
            linetype = "dashed") +
  geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                y = Aluminum_max, 
                                                color = "Aluminum_max (Ref)"), 
            linetype = "dotted")

```
```{r}
library(ggplot2)

# Plot the data for IRA scenario
p <- ggplot() +
  geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                y = Aluminum_mean, 
                                                color = "Aluminum_mean (IRA)"), 
            linetype = "solid") +
  geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                y = Aluminum_min, 
                                                color = "Aluminum_min (IRA)"), 
            linetype = "dashed") +
  geom_line(data = material_demand_sum_ira, aes(x = year, 
                                                y = Aluminum_max, 
                                                color = "Aluminum_max (IRA)"), 
            linetype = "dotted") +
  labs(title = "Annual Aluminum Demand",
       x = "Year",
       y = "Material Demand (Mton/year)",
       color = "Scenario") +
  scale_color_manual(values = c("Aluminum_mean (IRA)" = "red", 
                                "Aluminum_min (IRA)" = "red", 
                                "Aluminum_max (IRA)" = "red", 
                                "Aluminum_mean (Ref)" = "blue", 
                                "Aluminum_min (Ref)" = "blue", 
                                "Aluminum_max (Ref)" = "blue"),  # Color for each line
                     name = "Scenario",
                     labels = c("Mean (IRA)", "Min (IRA)", "Max (IRA)", "Mean (Ref)", "Min (Ref)", "Max (Ref)")) +
  theme_minimal()

# Plot the data for Ref scenario and combine with the previous plot
p1<-p +
  geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                y = Aluminum_mean, 
                                                color = "Aluminum_mean (Ref)"), 
            linetype = "solid") +
  geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                y = Aluminum_min, 
                                                color = "Aluminum_min (Ref)"), 
            linetype = "dashed") +
  geom_line(data = material_demand_sum_ref, aes(x = year, 
                                                y = Aluminum_max, 
                                                color = "Aluminum_max (Ref)"), 
            linetype = "dotted")

```

```{r}

aluminum_subset <- multi_model_mc_material_demand_total %>%
  filter(Material == "Aluminum") %>% filter(year == "2025")%>% filter(scenario =="IRA")%>%
  select(-Coal, -Gas, -Hydro, -Nuclear.New, -onshore.wind, -utility.scale.solar.pv)

boxplot <- ggplot(aluminum_subset, aes(x = year, y = total_demand)) +
  geom_boxplot() +
  labs(x = "year", y = "Total Demand for Aluminum", title = "Box Plot of Total Demand for Aluminum")
print(boxplot)
p+boxplot
```
```{r}
# Assuming p is your ggplot object representing your existing plot

# Filter aluminum data for the specified conditions
aluminum_subset_ira <- multi_model_mc_material_demand_total %>%
  filter(Material == "Aluminum", year == "2035", scenario == "IRA") %>%
  select(-total_demand, -year, -scenario, -Material, -row_id) %>%
  mutate(
    onshore.wind = sort(onshore.wind),
    Hydro = sort(Hydro),
    Nuclear.New = sort(Nuclear.New),
    utility.scale.solar.pv = sort(utility.scale.solar.pv),
    Coal = sort(Coal),
    Gas = sort(Gas),
    total_demand = onshore.wind + Hydro + Nuclear.New + utility.scale.solar.pv + Coal + Gas,
    year = 2035
  )
print(min(aluminum_subset_ira$total_demand))
boxplot(aluminum_subset_ira$total_demand, 
        main = "Boxplot of Total Demand", 
        ylab = "Total Demand")



# Create a box plot for aluminum demand

# Combine the box plot with your existing plot p
combined_plot <- p1 + geom_boxplot(data = aluminum_subset_ira, aes(x = year, y = total_demand), fill = "gray", alpha = 0.5, width = 0.5) +
  labs(title = "Combined Plot with Box Plot of Aluminum Demand",
       x = "Year",
       y = "Material Demand (Mton/year)",
       color = "Scenario") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for better readability

# Print the combined plot
print(combined_plot)

```
```{r}
# Filter aluminum data for the specified conditions for scenario "Ref"
aluminum_subset_ref <- multi_model_mc_material_demand_total %>%
  filter(Material == "Aluminum", year == "2035", scenario == "Ref") %>%
  select(-total_demand, -year, -scenario, -Material, -row_id) %>%
  mutate(
    onshore.wind = sort(onshore.wind),
    Hydro = sort(Hydro),
    Nuclear.New = sort(Nuclear.New),
    utility.scale.solar.pv = sort(utility.scale.solar.pv),
    Coal = sort(Coal),
    Gas = sort(Gas),
    total_demand = onshore.wind + Hydro + Nuclear.New + utility.scale.solar.pv + Coal + Gas,
    year= 2035
  )

#mean_demand <- mean(aluminum_subset$total_demand)
#min_demand <- min(aluminum_subset$total_demand)
#max_demand <- max(aluminum_subset$total_demand)



# Create a box plot for aluminum demand for scenario "IRA"

# Create a box plot for aluminum demand for scenario "Ref"
boxplot_ref <- ggplot(aluminum_subset_ref, aes(x = year, y = total_demand)) +
  geom_boxplot(fill = "blue", alpha = 0.5, width = 0.5) +
  labs(x = "Year", y = "Total Demand for Aluminum (Ref)", title = "Box Plot of Total Demand for Aluminum (Ref)")

# Combine the box plots with your existing plot p
combined_plot <- p1 +
  geom_boxplot(data = aluminum_subset_ira, aes(x = year, y = total_demand), fill = "gray", alpha = 0.5, width = 0.5) +
  geom_boxplot(data = aluminum_subset_ref, aes(x = year, y = total_demand), fill = "blue", alpha = 0.5, width = 0.5) +
  labs(title = "Combined Plot with Box Plots of Aluminum Demand",
       x = "Year",
       y = "Material Demand (Mton/year)",
       color = "Scenario") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for better readability

# Print the combined plot
print(combined_plot)
# Define the width for staggering the box plots
stagger_width <- 0.1  # Adjust as needed

# Combine the box plots with your existing plot p, staggering them slightly
combined_plot <- p1 +
  geom_boxplot(data = aluminum_subset_ira, aes(x = year - stagger_width, y = total_demand), fill = "red", alpha = 0.5, width = 0.4) +
  geom_boxplot(data = aluminum_subset_ref, aes(x = year + stagger_width, y = total_demand), fill = "blue", alpha = 0.5, width = 0.4) +
  labs(title = "",
       x = "Year",
       y = "Material Demand (Mton/year)",
       color = "Scenario") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for better readability

# Print the combined plot
print(combined_plot)


```
```{r}
aluminum_subset_test <- multi_model_mc_material_demand_total %>%
  filter(Material == "Aluminum", year == "2035", scenario == "Ref") %>%
  select(-total_demand, -year, -scenario, -Material, -row_id) %>%
  mutate(
    onshore.wind = sort(onshore.wind),
    Hydro = sort(Hydro),
    Nuclear.New = sort(Nuclear.New),
    utility.scale.solar.pv = sort(utility.scale.solar.pv),
    Coal = sort(Coal),
    Gas = sort(Gas),
    total_demand = onshore.wind + Hydro + Nuclear.New + utility.scale.solar.pv + Coal + Gas
  )
```

